package pageobject.constants;

public enum NameOfTheButton {
    LOGIN_ON_HOME_PAGE_THROUGH_ENTER_ACCOUNT_BUTTON,
    LOGIN_ON_HOME_PAGE_THROUGH_PERSONAL_CABINET_BUTTON,
    LOGIN_ON_REGISTRATION_PAGE_BUTTON,
    LOGIN_ON_FORGOT_PASSWORD_PAGE_BUTTON
}